---
- name: Invoke AlgoSec
  hosts: [algosec_manager]
  connection: local
  gather_facts: false

  tasks:
  - name: Create Ticket
    include_role:
      name: algosec_provision_network_connectivity
      vars_from: "algosec-secrets.yml"
