---
- name: Create Host Record
  hosts: all
  connection: local
  gather_facts: false

  tasks:
  - name: Create Host Record
    include_role:
      name: algosec_provision_network_connectivity
      vars_from: "algosec-secrets.yml"
